# Python package

trigger:
- master

pool:

  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
    
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      import nltk
      nltk.download('stopwords')
      nltk.download('averaged_perceptron_tagger')
      nltk.download('wordnet')
  displayName: 'Library downloaders'

- script: |
    cd src
    python global_controller.py
  displayName: 'Run global controller'
  
# - task: PythonScript@0
#   inputs:
#     scriptSource: 'filePath'
#     scriptPath: 'global_controller.py'
#   displayName: 'Run global controller'