# Python package

trigger:
- master

pool:

  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
    
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python
    import nltk
    nltk.download('stopwords')
    exit()
  displayName: 'Install dependencies'
  
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'src/global_controller.py'